using System.Buffers.Binary;
using System.Text;

namespace ImgToStlPlate.API.Services;

public class StlGeneratorService : IStlGeneratorService
{
    private const string HeaderText = "Binary STL generated by ImgToStlPlate";
    private const int HeaderLength = 80;
    private const int TriangleCountOffset = HeaderLength;

    private readonly record struct Rect(int Row, int Col, int Width, int Height, double Level);

    private readonly record struct Cuts(bool[,] AlongColumns, bool[,] AlongRows);

    public byte[] GenerateStl(int[,] matrix, double thickness, double mmPerPixel, double whitePixelThicknessRatio)
    {
        int rows = matrix.GetLength(0);
        int cols = matrix.GetLength(1);

        var heights = BuildHeights(matrix, rows, cols, thickness, whitePixelThicknessRatio);
        var rectangles = MergeRectangles(heights, rows, cols);

        using var ms = new MemoryStream();
        WritePreamble(ms);

        int triangleCount = 0;

        if (rectangles.Count > 0)
        {
            var (centerX, centerY) = ComputeCenter(rectangles, mmPerPixel);
            var levels = CollectLevels(heights, rows, cols);
            var cuts = BuildCuts(rectangles, rows, cols);

            foreach (var rect in rectangles)
                triangleCount += WriteHorizontalFaces(ms, rect, cuts, mmPerPixel, centerX, centerY);

            triangleCount += WriteWalls(ms, heights, cuts, rows, cols, mmPerPixel, centerX, centerY, levels);
        }

        ms.Position = TriangleCountOffset;
        Span<byte> countBuffer = stackalloc byte[4];
        BinaryPrimitives.WriteInt32LittleEndian(countBuffer, triangleCount);
        ms.Write(countBuffer);

        return ms.ToArray();
    }

    private static void WritePreamble(MemoryStream ms)
    {
        var header = new byte[HeaderLength];
        Encoding.ASCII.GetBytes(HeaderText, 0, Math.Min(HeaderText.Length, HeaderLength), header, 0);
        ms.Write(header, 0, header.Length);
        ms.Write(new byte[4], 0, 4);
    }

    private static double[,] BuildHeights(int[,] matrix, int rows, int cols, double thickness, double whitePixelThicknessRatio)
    {
        var heights = new double[rows, cols];

        for (int row = 0; row < rows; row++)
        {
            for (int col = 0; col < cols; col++)
            {
                double height = matrix[row, col] switch
                {
                    1 => thickness,
                    0 => thickness * whitePixelThicknessRatio,
                    _ => 0.0
                };

                heights[row, col] = height > 0 ? height : 0.0;
            }
        }

        return heights;
    }

    private static List<Rect> MergeRectangles(double[,] heights, int rows, int cols)
    {
        var consumed = new bool[rows, cols];
        var result = new List<Rect>();

        for (int row = 0; row < rows; row++)
        {
            for (int col = 0; col < cols; col++)
            {
                if (consumed[row, col]) continue;

                double level = heights[row, col];
                if (level <= 0) continue;

                int endCol = col + 1;
                while (endCol < cols && !consumed[row, endCol] && heights[row, endCol] == level)
                    endCol++;

                int width = endCol - col;
                int height = 1;

                while (row + height < rows)
                {
                    bool allMatch = true;
                    for (int c = col; c < endCol; c++)
                    {
                        if (consumed[row + height, c] || heights[row + height, c] != level)
                        {
                            allMatch = false;
                            break;
                        }
                    }

                    if (!allMatch) break;
                    height++;
                }

                for (int r = row; r < row + height; r++)
                    for (int c = col; c < endCol; c++)
                        consumed[r, c] = true;

                result.Add(new Rect(row, col, width, height, level));
            }
        }

        return result;
    }

    private static (double CenterX, double CenterY) ComputeCenter(List<Rect> rectangles, double mmPerPixel)
    {
        double minX = double.MaxValue, minY = double.MaxValue;
        double maxX = double.MinValue, maxY = double.MinValue;

        foreach (var rect in rectangles)
        {
            double x0 = rect.Col * mmPerPixel;
            double y0 = rect.Row * mmPerPixel;
            double x1 = (rect.Col + rect.Width) * mmPerPixel;
            double y1 = (rect.Row + rect.Height) * mmPerPixel;

            if (x0 < minX) minX = x0;
            if (y0 < minY) minY = y0;
            if (x1 > maxX) maxX = x1;
            if (y1 > maxY) maxY = y1;
        }

        return ((minX + maxX) / 2.0, (minY + maxY) / 2.0);
    }

    private static double[] CollectLevels(double[,] heights, int rows, int cols)
    {
        var levels = new SortedSet<double> { 0.0 };

        for (int row = 0; row < rows; row++)
            for (int col = 0; col < cols; col++)
                if (heights[row, col] > 0)
                    levels.Add(heights[row, col]);

        return levels.ToArray();
    }

    private static Cuts BuildCuts(List<Rect> rectangles, int rows, int cols)
    {
        var owner = new int[rows, cols];
        for (int row = 0; row < rows; row++)
            for (int col = 0; col < cols; col++)
                owner[row, col] = -1;

        for (int index = 0; index < rectangles.Count; index++)
        {
            var rect = rectangles[index];
            for (int row = rect.Row; row < rect.Row + rect.Height; row++)
                for (int col = rect.Col; col < rect.Col + rect.Width; col++)
                    owner[row, col] = index;
        }

        int OwnerAt(int row, int col) =>
            row < 0 || row >= rows || col < 0 || col >= cols ? -1 : owner[row, col];

        var alongColumns = new bool[cols + 1, rows + 1];
        for (int col = 0; col <= cols; col++)
            for (int row = 0; row <= rows; row++)
                alongColumns[col, row] = row == 0 || row == rows
                    || OwnerAt(row - 1, col - 1) != OwnerAt(row, col - 1)
                    || OwnerAt(row - 1, col) != OwnerAt(row, col);

        var alongRows = new bool[rows + 1, cols + 1];
        for (int row = 0; row <= rows; row++)
            for (int col = 0; col <= cols; col++)
                alongRows[row, col] = col == 0 || col == cols
                    || OwnerAt(row - 1, col - 1) != OwnerAt(row - 1, col)
                    || OwnerAt(row, col - 1) != OwnerAt(row, col);

        return new Cuts(alongColumns, alongRows);
    }

    private static int WriteHorizontalFaces(MemoryStream ms, Rect rect, Cuts cuts, double mmPerPixel, double centerX, double centerY)
    {
        double x0 = rect.Col * mmPerPixel - centerX;
        double y0 = rect.Row * mmPerPixel - centerY;
        double x1 = (rect.Col + rect.Width) * mmPerPixel - centerX;
        double y1 = (rect.Row + rect.Height) * mmPerPixel - centerY;
        double z = rect.Level;

        var boundary = BuildBoundary(rect, cuts, mmPerPixel, centerX, centerY);

        if (boundary.Count == 4)
        {
            WriteTriangle(ms, x0, y0, z, x1, y0, z, x1, y1, z);
            WriteTriangle(ms, x0, y0, z, x1, y1, z, x0, y1, z);
            WriteTriangle(ms, x0, y0, 0, x1, y1, 0, x1, y0, 0);
            WriteTriangle(ms, x0, y0, 0, x0, y1, 0, x1, y1, 0);
            return 4;
        }

        double fanX = (x0 + x1) / 2.0;
        double fanY = (y0 + y1) / 2.0;

        for (int i = 0; i < boundary.Count; i++)
        {
            var a = boundary[i];
            var b = boundary[(i + 1) % boundary.Count];

            WriteTriangle(ms, fanX, fanY, z, a.X, a.Y, z, b.X, b.Y, z);
            WriteTriangle(ms, fanX, fanY, 0, b.X, b.Y, 0, a.X, a.Y, 0);
        }

        return boundary.Count * 2;
    }

    private static List<(double X, double Y)> BuildBoundary(Rect rect, Cuts cuts, double mmPerPixel, double centerX, double centerY)
    {
        int left = rect.Col;
        int right = rect.Col + rect.Width;
        int top = rect.Row;
        int bottom = rect.Row + rect.Height;

        var boundary = new List<(double X, double Y)>();

        for (int col = left; col < right; col++)
            if (cuts.AlongRows[top, col])
                boundary.Add((col * mmPerPixel - centerX, top * mmPerPixel - centerY));

        for (int row = top; row < bottom; row++)
            if (cuts.AlongColumns[right, row])
                boundary.Add((right * mmPerPixel - centerX, row * mmPerPixel - centerY));

        for (int col = right; col > left; col--)
            if (cuts.AlongRows[bottom, col])
                boundary.Add((col * mmPerPixel - centerX, bottom * mmPerPixel - centerY));

        for (int row = bottom; row > top; row--)
            if (cuts.AlongColumns[left, row])
                boundary.Add((left * mmPerPixel - centerX, row * mmPerPixel - centerY));

        return boundary;
    }

    private static int WriteWalls(MemoryStream ms, double[,] heights, Cuts cuts, int rows, int cols,
        double mmPerPixel, double centerX, double centerY, double[] levels)
    {
        int count = 0;

        for (int col = 0; col <= cols; col++)
        {
            int runStart = 0;

            for (int row = 1; row <= rows; row++)
            {
                if (!cuts.AlongColumns[col, row]) continue;

                double before = col > 0 ? heights[runStart, col - 1] : 0.0;
                double after = col < cols ? heights[runStart, col] : 0.0;

                if (before != after)
                {
                    double x = col * mmPerPixel - centerX;
                    double yA = runStart * mmPerPixel - centerY;
                    double yB = row * mmPerPixel - centerY;
                    bool facingPlusX = before > after;

                    foreach (var (bandLow, bandHigh) in Bands(levels, Math.Min(before, after), Math.Max(before, after)))
                    {
                        if (facingPlusX)
                            WriteQuad(ms, x, yA, bandLow, x, yB, bandLow, x, yB, bandHigh, x, yA, bandHigh);
                        else
                            WriteQuad(ms, x, yA, bandLow, x, yA, bandHigh, x, yB, bandHigh, x, yB, bandLow);

                        count += 2;
                    }
                }

                runStart = row;
            }
        }

        for (int row = 0; row <= rows; row++)
        {
            int runStart = 0;

            for (int col = 1; col <= cols; col++)
            {
                if (!cuts.AlongRows[row, col]) continue;

                double before = row > 0 ? heights[row - 1, runStart] : 0.0;
                double after = row < rows ? heights[row, runStart] : 0.0;

                if (before != after)
                {
                    double y = row * mmPerPixel - centerY;
                    double xA = runStart * mmPerPixel - centerX;
                    double xB = col * mmPerPixel - centerX;
                    bool facingPlusY = before > after;

                    foreach (var (bandLow, bandHigh) in Bands(levels, Math.Min(before, after), Math.Max(before, after)))
                    {
                        if (facingPlusY)
                            WriteQuad(ms, xA, y, bandLow, xA, y, bandHigh, xB, y, bandHigh, xB, y, bandLow);
                        else
                            WriteQuad(ms, xA, y, bandLow, xB, y, bandLow, xB, y, bandHigh, xA, y, bandHigh);

                        count += 2;
                    }
                }

                runStart = col;
            }
        }

        return count;
    }

    private static IEnumerable<(double Low, double High)> Bands(double[] levels, double low, double high)
    {
        double previous = low;

        foreach (double level in levels)
        {
            if (level <= previous) continue;
            if (level >= high) break;

            yield return (previous, level);
            previous = level;
        }

        if (high > previous)
            yield return (previous, high);
    }

    private static void WriteQuad(MemoryStream ms,
        double ax, double ay, double az,
        double bx, double by, double bz,
        double cx, double cy, double cz,
        double dx, double dy, double dz)
    {
        WriteTriangle(ms, ax, ay, az, bx, by, bz, cx, cy, cz);
        WriteTriangle(ms, ax, ay, az, cx, cy, cz, dx, dy, dz);
    }

    private static void WriteTriangle(MemoryStream ms,
        double px0, double py0, double pz0,
        double px1, double py1, double pz1,
        double px2, double py2, double pz2)
    {
        double e1x = px1 - px0, e1y = py1 - py0, e1z = pz1 - pz0;
        double e2x = px2 - px0, e2y = py2 - py0, e2z = pz2 - pz0;

        double nx = e1y * e2z - e1z * e2y;
        double ny = e1z * e2x - e1x * e2z;
        double nz = e1x * e2y - e1y * e2x;

        double length = Math.Sqrt(nx * nx + ny * ny + nz * nz);
        if (length > 0)
        {
            nx /= length;
            ny /= length;
            nz /= length;
        }
        else
        {
            nx = 0;
            ny = 0;
            nz = 0;
        }

        Span<byte> buffer = stackalloc byte[50];
        int offset = 0;

        WriteFloat(buffer, ref offset, nx);
        WriteFloat(buffer, ref offset, ny);
        WriteFloat(buffer, ref offset, nz);
        WriteFloat(buffer, ref offset, px0);
        WriteFloat(buffer, ref offset, py0);
        WriteFloat(buffer, ref offset, pz0);
        WriteFloat(buffer, ref offset, px1);
        WriteFloat(buffer, ref offset, py1);
        WriteFloat(buffer, ref offset, pz1);
        WriteFloat(buffer, ref offset, px2);
        WriteFloat(buffer, ref offset, py2);
        WriteFloat(buffer, ref offset, pz2);

        ms.Write(buffer);
    }

    private static void WriteFloat(Span<byte> buffer, ref int offset, double value)
    {
        BinaryPrimitives.WriteSingleLittleEndian(buffer.Slice(offset), (float)value);
        offset += 4;
    }
}
