using System.Buffers.Binary;
using System.Text;

namespace ImgToStlPlate.API.Services;

public class StlGeneratorService : IStlGeneratorService
{
    public byte[] GenerateStl(int[,] matrix, double thickness, double mmPerPixel, double zeroToHalfRatio)
    {
        int rows = matrix.GetLength(0);
        int cols = matrix.GetLength(1);

        var rectangles = MergeRectangles(matrix, rows, cols);

        double minX = double.MaxValue, minY = double.MaxValue;
        double maxX = double.MinValue, maxY = double.MinValue, maxZ = 0;

        foreach (var r in rectangles)
        {
            double x0 = r.Col * mmPerPixel;
            double y0 = r.Row * mmPerPixel;
            double x1 = (r.Col + r.Width) * mmPerPixel;
            double y1 = (r.Row + r.Height) * mmPerPixel;
            double h = r.Value == 1 ? thickness : thickness * zeroToHalfRatio;

            if (x0 < minX) minX = x0;
            if (y0 < minY) minY = y0;
            if (x1 > maxX) maxX = x1;
            if (y1 > maxY) maxY = y1;
            if (h > maxZ) maxZ = h;
        }

        double centerX = (minX + maxX) / 2.0;
        double centerY = (minY + maxY) / 2.0;
        double centerZ = maxZ / 2.0;

        using var ms = new MemoryStream();

        ms.Write(new byte[80], 0, 80);
        int countOffset = (int)ms.Position;
        ms.Write(new byte[4], 0, 4);

        int triangleCount = 0;

        foreach (var r in rectangles)
        {
            double x0 = r.Col * mmPerPixel - centerX;
            double y0 = r.Row * mmPerPixel - centerY;
            double x1 = (r.Col + r.Width) * mmPerPixel - centerX;
            double y1 = (r.Row + r.Height) * mmPerPixel - centerY;
            double h = r.Value == 1 ? thickness : thickness * zeroToHalfRatio;

            triangleCount += WriteCuboidTriangles(ms, x0, y0, x1, y1, h);
        }

        ms.Position = countOffset;
        BinaryPrimitives.WriteInt32LittleEndian(ms.GetBuffer().AsSpan(countOffset), triangleCount);

        ms.Position = 0;
        var headerText = Encoding.ASCII.GetBytes("Binary STL generated by ImgToStlPlate");
        ms.Write(headerText, 0, Math.Min(headerText.Length, 80));

        return ms.ToArray();
    }

    private static List<(int Row, int Col, int Width, int Height, int Value)> MergeRectangles(int[,] matrix, int rows, int cols)
    {
        var consumed = new bool[rows, cols];
        var result = new List<(int Row, int Col, int Width, int Height, int Value)>();

        for (int i = 0; i < rows; i++)
        {
            for (int j = 0; j < cols; j++)
            {
                if (consumed[i, j] || matrix[i, j] < 0) continue;

                int value = matrix[i, j];
                int endCol = j + 1;
                while (endCol < cols && !consumed[i, endCol] && matrix[i, endCol] == value)
                    endCol++;

                int spanWidth = endCol - j;

                int spanHeight = 1;
                while (i + spanHeight < rows)
                {
                    bool allMatch = true;
                    for (int c = j; c < endCol; c++)
                    {
                        if (consumed[i + spanHeight, c] || matrix[i + spanHeight, c] != value)
                        {
                            allMatch = false;
                            break;
                        }
                    }
                    if (!allMatch) break;
                    spanHeight++;
                }

                for (int r = i; r < i + spanHeight; r++)
                    for (int c = j; c < endCol; c++)
                        consumed[r, c] = true;

                result.Add((i, j, spanWidth, spanHeight, value));
            }
        }

        return result;
    }

    private static int WriteCuboidTriangles(MemoryStream ms,
        double x0, double y0, double x1, double y1, double h)
    {
        // Top face (z = h)
        WriteTriangle(ms, x0, y0, h, x1, y0, h, x1, y1, h);
        WriteTriangle(ms, x0, y0, h, x1, y1, h, x0, y1, h);

        // Bottom face (z = 0)
        WriteTriangle(ms, x0, y0, 0, x1, y1, 0, x1, y0, 0);
        WriteTriangle(ms, x0, y0, 0, x0, y1, 0, x1, y1, 0);

        // Front face (y = y0)
        WriteTriangle(ms, x0, y0, 0, x1, y0, 0, x1, y0, h);
        WriteTriangle(ms, x0, y0, 0, x1, y0, h, x0, y0, h);

        // Back face (y = y1)
        WriteTriangle(ms, x0, y1, 0, x1, y1, h, x1, y1, 0);
        WriteTriangle(ms, x0, y1, 0, x0, y1, h, x1, y1, h);

        // Left face (x = x0)
        WriteTriangle(ms, x0, y0, 0, x0, y1, h, x0, y1, 0);
        WriteTriangle(ms, x0, y0, 0, x0, y0, h, x0, y1, h);

        // Right face (x = x1)
        WriteTriangle(ms, x1, y0, 0, x1, y1, 0, x1, y1, h);
        WriteTriangle(ms, x1, y0, 0, x1, y1, h, x1, y0, h);

        return 12;
    }

    private static void WriteTriangle(MemoryStream ms,
        double px0, double py0, double pz0,
        double px1, double py1, double pz1,
        double px2, double py2, double pz2)
    {
        // Compute face normal
        double e1x = px1 - px0, e1y = py1 - py0, e1z = pz1 - pz0;
        double e2x = px2 - px0, e2y = py2 - py0, e2z = pz2 - pz0;
        double nx = e1y * e2z - e1z * e2y;
        double ny = e1z * e2x - e1x * e2z;
        double nz = e1x * e2y - e1y * e2x;

        // Binary STL: 12 floats (4 bytes each) + 2 bytes attribute = 50 bytes
        Span<byte> buf = stackalloc byte[50];
        int offset = 0;

        WriteFloat(buf, ref offset, nx);
        WriteFloat(buf, ref offset, ny);
        WriteFloat(buf, ref offset, nz);
        WriteFloat(buf, ref offset, px0);
        WriteFloat(buf, ref offset, py0);
        WriteFloat(buf, ref offset, pz0);
        WriteFloat(buf, ref offset, px1);
        WriteFloat(buf, ref offset, py1);
        WriteFloat(buf, ref offset, pz1);
        WriteFloat(buf, ref offset, px2);
        WriteFloat(buf, ref offset, py2);
        WriteFloat(buf, ref offset, pz2);

        ms.Write(buf);
    }

    private static void WriteFloat(Span<byte> buf, ref int offset, double value)
    {
        BinaryPrimitives.WriteSingleLittleEndian(buf.Slice(offset), (float)value);
        offset += 4;
    }
}
