using System.Buffers.Binary;
using System.Text;

namespace ImgToStlPlate.API.Services;

public class StlGeneratorService : IStlGeneratorService
{
    public byte[] GenerateStl(int[,] matrix, double thickness, double mmPerPixel, double zeroToHalfRatio)
    {
        int rows = matrix.GetLength(0);
        int cols = matrix.GetLength(1);

        using var ms = new MemoryStream();

        // Header placeholder (80 bytes)
        ms.Write(new byte[80], 0, 80);

        // Triangle count placeholder (4 bytes)
        int countOffset = (int)ms.Position;
        ms.Write(new byte[4], 0, 4);

        int triangleCount = 0;

        for (int i = 0; i < rows; i++)
        {
            for (int j = 0; j < cols; j++)
            {
                if (matrix[i, j] < 0) continue;

                double h = matrix[i, j] == 1 ? thickness : thickness * zeroToHalfRatio;
                double x0 = j * mmPerPixel;
                double y0 = i * mmPerPixel;
                double x1 = (j + 1) * mmPerPixel;
                double y1 = (i + 1) * mmPerPixel;

                triangleCount += WriteCuboidTriangles(ms, x0, y0, x1, y1, h);
            }
        }

        // Write triangle count
        ms.Position = countOffset;
        BinaryPrimitives.WriteInt32LittleEndian(ms.GetBuffer().AsSpan(countOffset), triangleCount);

        // Write header
        ms.Position = 0;
        var headerText = Encoding.ASCII.GetBytes("Binary STL generated by ImgToStlPlate");
        ms.Write(headerText, 0, Math.Min(headerText.Length, 80));

        return ms.ToArray();
    }

    private static int WriteCuboidTriangles(MemoryStream ms,
        double x0, double y0, double x1, double y1, double h)
    {
        // Top face (z = h)
        WriteTriangle(ms, x0, y0, h, x1, y0, h, x1, y1, h);
        WriteTriangle(ms, x0, y0, h, x1, y1, h, x0, y1, h);

        // Bottom face (z = 0)
        WriteTriangle(ms, x0, y0, 0, x1, y1, 0, x1, y0, 0);
        WriteTriangle(ms, x0, y0, 0, x0, y1, 0, x1, y1, 0);

        // Front face (y = y0)
        WriteTriangle(ms, x0, y0, 0, x1, y0, 0, x1, y0, h);
        WriteTriangle(ms, x0, y0, 0, x1, y0, h, x0, y0, h);

        // Back face (y = y1)
        WriteTriangle(ms, x0, y1, 0, x1, y1, h, x1, y1, 0);
        WriteTriangle(ms, x0, y1, 0, x0, y1, h, x1, y1, h);

        // Left face (x = x0)
        WriteTriangle(ms, x0, y0, 0, x0, y1, h, x0, y1, 0);
        WriteTriangle(ms, x0, y0, 0, x0, y0, h, x0, y1, h);

        // Right face (x = x1)
        WriteTriangle(ms, x1, y0, 0, x1, y1, 0, x1, y1, h);
        WriteTriangle(ms, x1, y0, 0, x1, y1, h, x1, y0, h);

        return 12;
    }

    private static void WriteTriangle(MemoryStream ms,
        double px0, double py0, double pz0,
        double px1, double py1, double pz1,
        double px2, double py2, double pz2)
    {
        // Compute face normal
        double e1x = px1 - px0, e1y = py1 - py0, e1z = pz1 - pz0;
        double e2x = px2 - px0, e2y = py2 - py0, e2z = pz2 - pz0;
        double nx = e1y * e2z - e1z * e2y;
        double ny = e1z * e2x - e1x * e2z;
        double nz = e1x * e2y - e1y * e2x;

        // Binary STL: 12 floats (4 bytes each) + 2 bytes attribute = 50 bytes
        Span<byte> buf = stackalloc byte[50];
        int offset = 0;

        WriteFloat(buf, ref offset, nx);
        WriteFloat(buf, ref offset, ny);
        WriteFloat(buf, ref offset, nz);
        WriteFloat(buf, ref offset, px0);
        WriteFloat(buf, ref offset, py0);
        WriteFloat(buf, ref offset, pz0);
        WriteFloat(buf, ref offset, px1);
        WriteFloat(buf, ref offset, py1);
        WriteFloat(buf, ref offset, pz1);
        WriteFloat(buf, ref offset, px2);
        WriteFloat(buf, ref offset, py2);
        WriteFloat(buf, ref offset, pz2);

        ms.Write(buf);
    }

    private static void WriteFloat(Span<byte> buf, ref int offset, double value)
    {
        BinaryPrimitives.WriteSingleLittleEndian(buf.Slice(offset), (float)value);
        offset += 4;
    }
}
